version: "3.9"

services:
  gateway:
    container_name: gateway
    build:
      context: ./gateway
    restart: always
    ports:
      - 8080:8080
    volumes:
      - ./gateway/config/gateway.conf:/etc/nginx/nginx.conf:ro

  service-auth:
    build:
      context: ./auth
    container_name: service-auth
    restart: always
    expose:
      - 5000
    env_file:
      - ./auth/.env
    volumes:
      - ./auth/db.sqlite:/back/auth/db.sqlite

  service-market:
    build:
      context: ./market
    container_name: service-market
    restart: always
    expose:
      - 6000
    env_file:
      - ./market/.env
    volumes:
      - ./market/db.sqlite:/back/market/db.sqlite
